language: php

php:
    - 5.4

before_script:
    - cp behat.yml{-dist,}
    - composer install

script:
    - ./bin/behat -fprogress

    - ./bin/box build
    - sed -i 's/Behatch\\Notifier\\Extension/behatch_notifiers.phar/' behat.yml
    - ./bin/behat -fprogress
